### ISSUE TITLE
Master: Turret mode

### ISSUE THREAD

**Issue by Bone008** [Bone008/HackerJedi#21]
As a special ability for the master.

The eye transforms into a giant (non-moving) turret thing.

Master switches into 1st person mode and fires giant lasers.

Hacker can dodge in slomo.

**Comment by PeterGreth** [comment]
As of f01d548:
- Master can place turrets
- The cam will transition to the turret
- For 10 seconds, the master can shoot (currently without effect I guess)
- The cam will transition back to the eye

During transitions, the master cannot interact with anything.
Sorry, didn't see it was nicetohave...

**Comment by PeterGreth** [comment]
Shooting incidentally already works, the turret can damage both enemies and the hacker

**Comment by Bone008** [comment]
This is done, we just need to integrate the turret model (see #53).
