### ISSUE TITLE
Handle multiple platform blocker

### ISSUE THREAD

**Issue by PeterGreth** [Bone008/HackerJedi#25]
Problem:
HackerTerminal -> Platform blocked
SuicideEnemy -> Platform also blocked for 2 secs -> Platform moving through HackerTerminal

I guess we need some sort of functionality to register multiple scripts as Platform-Blockers

**Comment by Bone008** [comment]
A possible solution would be to only track "blocked for x seconds" in the platform script that usually just ticks down to 0.

HackerTerminal sets this to some value >0 each frame as long as it is active, SuicideEnemies sets it to 2 once when exploding.

The variable can only be increased by blocker-scripts, not decreased.
