### ISSUE TITLE
Help needed: Improve curved UI script to work on all screens

### ISSUE THREAD

**Issue by PeterGreth** [Bone008/HackerJedi#30]
Currently the curved ui (e.g. Master buttons) looks different on different screens and also is unusable on some screens.

**Comment by PeterGreth** [comment]
For now, maybe use normal buttons

**Comment by Bone008** [comment]
I fixed the tessellation script, fixed the UI clipping behind the world and searched for way too long for a way to fix the raycaster so input works properly ...

It's madness, there must be some wrong calculations in the `CylinderMapping`, the projected line just doesn't match the displacement of the shader.

So I decided that we will just dump Curved UI and use a normal screen space canvas - with angled buttons so they look somewhat 3D (like in [this picture](https://docs.unity3d.com/uploads/Main/GUI_Canvas_Screenspace_Camera.png)).

**Comment by Bone008** [comment]
Removed Curved UI in 11e6bb0. Now everything at least works.
