### ISSUE TITLE
Broken enemies

### ISSUE THREAD

**Issue by PeterGreth** [Bone008/HackerJedi#32]
They
- clip together/stuck inside each other
- when thrown on the ground, teleport into upright position -> smooth move up

**Comment by PeterGreth** [comment]
When placed outside the grid, navmesh agent complains...stupid fuck

**Comment by PeterGreth** [comment]
Enemies drifting away

**Comment by Bone008** [comment]
@kpwfenins After 2fe4837 the problem has improved a bit, but when pushing enemies around with jedi forces, they tumble around helplessly and don't stop rotating (--> `angularVelocity` of the rigidbody).

**Comment by Bone008** [comment]
Pretty much fixed (mostly by Moritz).
