### ISSUE TITLE
Add enemy/obstacle placing success indicator

### ISSUE THREAD

**Issue by PeterGreth** [Bone008/HackerJedi#47]
Currently the master-player doesnt know if he can place an enemy/obstacle. Reasons for / solutions to failure may be
- not enough money
  - ~~add cost of enemies to master gui buttons~~
  - ~~disable buttons if not enough money~~
- spawn point too close to platform
  - grey-out [rail] blocks that are not available for spawning

or we just show an error message indicating why he cant place it there...

**Comment by Bone008** [comment]
I think this is crucial information for the Master!

**Comment by PeterGreth** [comment]
How to do the spawn zone?
Changing the color of anything requires different shaders for hacker/master because the hacker shouldn't see the area. -> some sort of different colored panels only visible to the master on top of the blocks in the no-spawn zone?

**Comment by Bone008** [comment]
Yes, that sounds good. A `NotVisibleToHacker` layer is probably necessary?

I would either add a child on that layer to the Block prefab that can then be enabled/disabled as needed, or try to find a more efficient way (maybe just draw a big red circle around the platform?).
