### ISSUE TITLE
Take out all testing hotkeys and stuff

### ISSUE THREAD

**Issue by kpwfenins** [Bone008/HackerJedi#76]
take out cheat command c, recording camera and f8 to switch perspectives. More?

**Comment by PeterGreth** [comment]
Do we really want to do that? Imho it also makes things easier for the grading

**Comment by kpwfenins** [comment]
at least recording cam :D

**Comment by kpwfenins** [comment]
Also L for level generation, big no no

**Comment by Bone008** [comment]
Removing L is fine, as it kinda breaks the level, I would argue for the other cheats to stay, maybe just make them harder to reach so you don't accidentally hit them?

I think most of the time when we start the game, we need those shortcuts for better demonstration.

**Comment by PeterGreth** [comment]
Fixed by cf0a678
